#!/usr/bin/env python3
"""Download the site's Google Fonts and write them into tools/offline-fonts.css
as data URIs, so build-offline.py needs no network.

Run this again only if a page starts using a new family or weight. Needs curl.
"""
import base64, pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).resolve().parent

# The union of every family/weight any page asks for. Keep in step with the
# <link href="https://fonts.googleapis.com/css2?..."> tags in the pages.
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Herr+Von+Muellerhoff"
    "&family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400"
    "&family=Jost:wght@300;400;500;600"
    "&family=IBM+Plex+Mono:wght@400;500"
    "&display=swap"
)

# A woff2 is only served to a browser-like client.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/120.0.0.0 Safari/537.36")

# The site is English and German only. Every non-ASCII character it uses —
# umlauts, ss, e-acute, the quotes and dashes — is inside Google's "latin"
# subset, so the rest are dead weight. The few that are not (an arrow and two
# emoji) fall back to a system font on the live site as well.
KEEP_SUBSETS = {"latin"}


def fetch(url: str) -> bytes:
    out = subprocess.run(["curl", "-sSfL", "-A", UA, url], capture_output=True)
    if out.returncode != 0:
        sys.exit("failed to fetch %s\n%s" % (url, out.stderr.decode("utf-8", "replace")))
    return out.stdout


def main() -> None:
    css = fetch(CSS_URL).decode("utf-8")

    # Google emits "/* subset */" ahead of each @font-face; split on those.
    parts = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    blocks, kept, dropped = [], 0, 0
    for i in range(1, len(parts) - 1, 2):
        subset, body = parts[i].strip(), parts[i + 1]
        if subset not in KEEP_SUBSETS:
            dropped += 1
            continue
        urls = re.findall(r"url\((https://[^)]+\.woff2)\)", body)
        for u in urls:
            data = fetch(u)
            uri = "data:font/woff2;base64," + base64.b64encode(data).decode("ascii")
            body = body.replace(u, uri)
            kept += 1
        blocks.append("/* %s */%s" % (subset, body.rstrip()))

    header = (
        "/* Generated by tools/fetch-fonts.py — do not edit by hand.\n"
        " * The site's Google Fonts, %s subsets only, inlined as data URIs so\n"
        " * the offline bundle renders with no network. */\n" % "+".join(sorted(KEEP_SUBSETS))
    )
    dest = HERE / "offline-fonts.css"
    dest.write_text(header + "\n".join(blocks) + "\n", encoding="utf-8")
    print("wrote %s — %d faces inlined, %d non-latin faces dropped, %.0f KB"
          % (dest.name, kept, dropped, dest.stat().st_size / 1024))


if __name__ == "__main__":
    main()
